# Site settings
title: MyCo from Stockflare
email: info@stockflare.com
description: "MyCO explores great brands that are listed on the stock market. Why not see if the brand you like has the potential to be a great investments?"
baseurl: "https://stockflare.com"
url: "http://my.stockflare.com"

# Build settings
markdown: kramdown
permalink: pretty
